## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

addons:
  apt:
    packages:
    - gfortran

notifications:
  email: false

branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/   

matrix:
  allow_failures:
  - julia: nightly

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc || true;
      brew link --overwrite gcc;
      export FC=gfortran;
    fi

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MakeFshared")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
